### ISSUE TITLE
History helper chart always shows account id even when username is available

### ISSUE THREAD

**Issue by zaitsev11-dev** [maxrioux100/gamestop-nft-helper#1]
History helper chart always shows account id even when username is available.

Steps to reproduce:
1. Ensure extension is installed & updated
2. Load an NTF at https://nft.gamestop.com/token/<token address>
3. Ensure that the NFT has >1 number of transactions
4. Ensure that the History helper chart is loaded
5. Mouse over the History helper chart.
6. Observe the chart labels

Current behavior:
The account ids are minimized (does not show the full account id).

Expected behavior:
If a username exists, it should show up in the mouse over event label.

How to resolve:
Use the value for the `href` instead of using the innerText value for each element under `HistoryItemWrapper.p.span[n].strong.a` where n=0 is the buyer and n=1 is the seller. Split the `href` value to only obtain the username.

**Comment by maxrioux100** [comment]
Okay, I will make the change :)

**Comment by zaitsev11-dev** [comment]
There appears to be a race condition between the plugin and the marketplace. The current marketplace seems to first populate the account id in the history table then update the data where usernames are known to exist by making an ASYNC call to `https://api.nft.gamestop.com/nft-svc-marketplace/getPublicProfile?address=<>`. I'm not sure how we would be able to check when this subsequent process is known to be finished.

I started a Pull Request here which obtains the full account ids from the `href` field, but does not pull username due to the aforementioned finding.
https://github.com/maxrioux100/gamestop-nft-helper/pull/7

**Comment by maxrioux100** [comment]
OK' I'm on it
