### ISSUE TITLE
Offers helper text should prompt opening the "editions" slider

### ISSUE THREAD

**Issue by zaitsev11-dev** [maxrioux100/gamestop-nft-helper#2]
Existing functionality:
the "Offers helper" chart is surfaced when the "Editions" button is clicked.

Proposed functionality:
"Offers helper" header should be created upon page load. Text should exist under this header to prompt the user to open the "Editions" button in order to load the data. Once the editions button has been clicked and the slider tray has been closed, the text prompt should be replaced with the Offers helper chart.

**Comment by maxrioux100** [comment]
I open my issues on gitlab and it was already planned there :). I was experimenting about some graph placement before doing this one.
