### ISSUE TITLE
Error: <svg> attribute height: Expected length, "NaN"

### ISSUE THREAD

**Issue by zaitsev11-dev** [maxrioux100/gamestop-nft-helper#28]
I noticed the Google Chrome extension had a few error messages, it seems that these are related to the Apex chart implementation.

![2022-07-18 18_47_19-Extensions](https://user-images.githubusercontent.com/109398307/179647592-6d093adb-78b3-42bf-bc82-a998bd6941fd.png)

This is the URL that is referenced in the error message context:
https://nft.gamestop.com/token/0xe78b7d9abacffe9616a36a2a2f31e5cd47b0db08/0x6361ee9e22851912610b33ccafa44bce4eef8bacd8b98dfac4bdc8de5976d368

**Comment by zaitsev11-dev** [comment]
I noticed that there are many different error messages from the Chrome extension page:

```
Error: <svg> attribute height: Expected length, "NaN".
Error: <path> attribute d: Expected number, "M 0 NaN".
Error: <g> attribute transform: Expected number, "translate(NaN, 0)".
Error: <svg> attribute height: Expected length, "NaN".
Error: <path> attribute d: Expected number, "M 0 NaN".
Error: <g> attribute transform: Expected number, "translate(NaN, 0)".
Error: <svg> attribute height: Expected length, "NaN".
Error: <path> attribute d: Expected number, "M 0 NaN".
Error: <g> attribute transform: Expected number, "translate(NaN, 0)".
Error: <svg> attribute height: Expected length, "NaN".
Error: <path> attribute d: Expected number, "M 0 NaN".
Error: <g> attribute transform: Expected number, "translate(NaN, 0)".
Error: <svg> attribute height: Expected length, "NaN".
Error: <path> attribute d: Expected number, "M 0 NaN".
Error: <g> attribute transform: Expected number, "translate(NaN, 0)".
Error: <svg> attribute height: Expected length, "NaN".
Error: <path> attribute d: Expected number, "M 0 NaN".
Error: <g> attribute transform: Expected number, "translate(NaN, 0)".
```

**Comment by maxrioux100** [comment]
Yes, it's the cart object that is not deleted when the div containing it is. It happen when you go on a page with no history after going on a page with an history

**Comment by maxrioux100** [comment]
The bug is not causing any problem except the errors

**Comment by maxrioux100** [comment]
I don't know how to solve it

**Comment by zaitsev11-dev** [comment]
The bug stemmed from the decision to use onUrlChange observer without checking if the chart already exists on page.

**Comment by zaitsev11-dev** [comment]
This issue appears in the Apex charts repo. Specifically, this comment seems to be very similar to the issue that we are encountering.

https://github.com/apexcharts/apexcharts.js/issues/2270#issuecomment-943375831

**Comment by zaitsev11-dev** [comment]
Unfortunately it appears that this issue persists in the `main` branch. See the errors I have received recently:
![2022-07-23 17_41_58-Extensions](https://user-images.githubusercontent.com/109398307/180627504-ec78e33e-acd3-4d87-9102-62f19dd7d45a.png)

The errors definitely appear less frequently, but I have noticed them on occasion.

**Comment by zaitsev11-dev** [comment]
I have not experienced this issue again, so it seems to be quite rare.
