### ISSUE TITLE
Remove X axis labels from Offers helper chart 

### ISSUE THREAD

**Issue by zaitsev11-dev** [maxrioux100/gamestop-nft-helper#3]
The X axis labels are unnecessary in the Offers helper chart since this number is visible upon the mouse hover event. Futhermore, the X axis labels are overlaid on top of each other in NFTs with a large number of transactions, rendering them unusable.

This is a lower priority issue.

**Comment by maxrioux100** [comment]
Thanks about the feedback. I didn't know what to do about this one.
