### ISSUE TITLE
Authenticated user indicator representing NFT purchase price in History helper chart

### ISSUE THREAD

**Issue by zaitsev11-dev** [maxrioux100/gamestop-nft-helper#31]
When user is authenticated (signed in) and viewing an NFT that they own, it would be useful to have a dot within the history helper chart which represents the price point that the authenticated user purchased the NFT.

Requirements:
- If a user's name shows up as a buyer in the history helper, then a dot of a specific color is placed (perhaps green).
- If a user's name shows up as a seller in the history helper, then a dot of a different specific color is placed (perhaps red).

Note:  If a user buys and sells an NFT multiple times, then there will be multiple colored dots.

Out of scope:
We will not be pairing multiple purchases with multiple sales.

**Comment by maxrioux100** [comment]
How de we know the buying price ? We can only see the purchase from the logged user but we have no way of differentiating them and our pruchase could not even be on the history.

**Comment by zaitsev11-dev** [comment]
It does not seem like the username is visible in the DOM on an NFT web page without clicking on the profile icon. Thus in order to obtain the user's username (or account id), I propose this solution:

Use the [chrome.storage API](https://developer.chrome.com/docs/extensions/reference/storage/) to persist the username/account id value when the user navigates to the their profile page OR clicks on the profile icon from within the NFT page.

The assumption is that a user will not be using multiple accounts and thus we could reference the local storage across NFT pages without requiring the user to click on the profile icon for each page load.
