### ISSUE TITLE
add a menu to choose which option are active

### ISSUE THREAD

**Issue by maxrioux100** [maxrioux100/gamestop-nft-helper#38]

**Comment by zaitsev11-dev** [comment]
What options did you have in mind for this menu?

**Comment by maxrioux100** [comment]
Choose which one is active

Activate or not the history price (if active, the graph show, if not, the graph doesn't show)

The same for every options

**Comment by maxrioux100** [comment]
Like a list of checkbox

**Comment by zaitsev11-dev** [comment]
An option page would also be useful to enable/disable local storage such as #31

**Comment by zaitsev11-dev** [comment]
We could add an options menu as a new `<div>` within the profile page found at https://nft.gamestop.com/profile
