### ISSUE TITLE
No data shows up in Offer helper chart for NFTs with few editions

### ISSUE THREAD

**Issue by zaitsev11-dev** [maxrioux100/gamestop-nft-helper#5]
When clicking on the "Editions" button and the chart appears, however there is no data available in the chart even though data was available in the "Editions" slider tray.

This NFT currently has 2 editions available to purchase:
https://nft.gamestop.com/token/0xa327d6f2c31db791ce2e491fbf3ad6c226999ea8/0x7d22f63b425a13e46981779fd749376f5d8196e52868d947516c5b9fbfc6fafc

This NFT currently has 2 editions available to purchase:
https://nft.gamestop.com/token/0xd609f93080383f759e41791bcf07f0b65bac651c/0xf4fddc5571d786fc486c09a81f99c92cfcec9fc1253c44af763593d42259fb35

**Comment by maxrioux100** [comment]
It may have something to do with my outliers function. To delete abhorrent data, I'm on it
