### ISSUE TITLE
Sometime transactions that shouldn't be split are splitted

### ISSUE THREAD

**Issue by maxrioux100** [maxrioux100/gamestop-nft-helper#65]

**Comment by maxrioux100** [comment]
https://nft.gamestop.com/token/0x50f7c99091522898b3e0b8a5b4bd2d48385fe99e/0xb8d81226153e11a707ddd2ffd12f480e60d7a625f5c832c4512eebf1d9a554d9

**Comment by zaitsev11-dev** [comment]
I discovered network API calls being made when loading the above URL. These include an `amount` value.

See here:
https://api.nft.gamestop.com/nft-svc-marketplace/history?nftData=0x20c7f321f7d800f38f3fb62fd89cbfc28072feea226c0bc9bde0efc2ce008f01

Note that there are are a few unique ids such as 
`nftId` and `nftData`

These can be obtained via this API call, which can be constructed using the NFT URL (delimit by the forward slash character.)
```
https://api.nft.gamestop.com/nft-svc-marketplace/getNft?tokenIdAndContractAddress=0xb8d81226153e11a707ddd2ffd12f480e60d7a625f5c832c4512eebf1d9a554d9_0x50f7c99091522898b3e0b8a5b4bd2d48385fe99e
```

**Comment by maxrioux100** [comment]
Wow great find !
