### ISSUE TITLE
Opening NFT in new tab does not load the extension data

### ISSUE THREAD

**Issue by zaitsev11-dev** [maxrioux100/gamestop-nft-helper#70]
Opening NFT in new tab does not load the extension data

Steps to reproduce:
1. Navigate to NFT profile
2. Right click on NFT -> Open in new tab
3. Switch to new tab

Observed behavior:
There is no extension data (charts, tables, etc) added to the page.

Expected behavior:
The extension data (charts, tables, etc) should be added to the page.

**Comment by maxrioux100** [comment]
Can't repro
