### ISSUE TITLE
Test to anchor the nft image to the screen (and the current price) so they are always showing even when scrolled

### ISSUE THREAD

**Issue by maxrioux100** [maxrioux100/gamestop-nft-helper#96]

**Comment by zaitsev11-dev** [comment]
Ah very cool idea

**Comment by zaitsev11-dev** [comment]
Maybe this is a nit pick, but when scrolling slowly, the NFT and editions modals seem to jump to the top of the screen. Is it possible to make the anchor scroll smoother?

Screenshots attached
![2022-07-29 22_15_09-Raise a Glass to the Future_ Launch Week Edition - NFT by RumRunners _ GameStop ](https://user-images.githubusercontent.com/109398307/181875872-d8d15e9b-edbe-4a86-8985-155c78e07121.png)
![2022-07-29 22_15_24-Raise a Glass to the Future_ Launch Week Edition - NFT by RumRunners _ GameStop ](https://user-images.githubusercontent.com/109398307/181875874-986350ec-798d-4dde-b2ed-107ba8aa7ef9.png)
![2022-07-29 22_15_36-Raise a Glass to the Future_ Launch Week Edition - NFT by RumRunners _ GameStop ](https://user-images.githubusercontent.com/109398307/181875875-eb4d1a53-3a23-4a1a-ad50-583d41f2e554.png)
![2022-07-29 22_14_55-Raise a Glass to the Future_ Launch Week Edition - NFT by RumRunners _ GameStop ](https://user-images.githubusercontent.com/109398307/181875876-ba9a861a-874f-4c07-8c74-1fe23f46d747.png)
.

**Comment by maxrioux100** [comment]
> Maybe this is a nit pick, but when scrolling slowly, the NFT and editions modals seem to jump to the top of the screen. Is it possible to make the anchor scroll smoother?
> 
> Screenshots attached ![2022-07-29 22_14_55-Raise a Glass to the Future_ Launch Week Edition - NFT by RumRunners _ GameStop ](https://user-images.githubusercontent.com/109398307/181875876-ba9a861a-874f-4c07-8c74-1fe23f46d747.png) ![2022-07-29 22_15_09-Raise a Glass to the Future_ Launch Week Edition - NFT by RumRunners _ GameStop ](https://user-images.githubusercontent.com/109398307/181875872-d8d15e9b-edbe-4a86-8985-155c78e07121.png) ![2022-07-29 22_15_24-Raise a Glass to the Future_ Launch Week Edition - NFT by RumRunners _ GameStop ](https://user-images.githubusercontent.com/109398307/181875874-986350ec-798d-4dde-b2ed-107ba8aa7ef9.png) ![2022-07-29 22_15_36-Raise a Glass to the Future_ Launch Week Edition - NFT by RumRunners _ GameStop ](https://user-images.githubusercontent.com/109398307/181875875-eb4d1a53-3a23-4a1a-ad50-583d41f2e554.png)

How is it now?
