### ISSUE TITLE
Number of copies to buy should be integer

### ISSUE THREAD

**Issue by zaitsev11-dev** [maxrioux100/gamestop-nft-helper#98]
![image](https://user-images.githubusercontent.com/109398307/181876085-efdea345-4708-4c2a-8e41-126c2dfd9371.png)

**Comment by maxrioux100** [comment]
Yes, it is a temporary fixes. Before it was using integer but it was just writing them as integer, their value was still float. I need to check into this but this is a low priority

**Comment by zaitsev11-dev** [comment]
It looks like this was not resolved . As of 1.2.1, I still see decimals on this chart

![image](https://user-images.githubusercontent.com/109398307/182505871-1be089b6-5bea-4b99-b9e4-06969057e39a.png)

**Comment by maxrioux100** [comment]
It's because it's not merged to main yet
